### PR TITLE
 CI: Restore release action and add semver checks to CI deploy job

### PR DESCRIPTION
**Pull request by jschwe**
This MR restores the release action, which creates a github release upon tag.
We now use the github-cli to release the release instead of the third party action, which is not allowed by mozilla.

### CODE REVIEW

**Comment by jschwe** [comment]
For this to work, the following actions would need to be allowed by mozilla:

- obi1kenobi/cargo-semver-checks-action (could be worked around by manually installing and using cargo-semver-checks)
- softprops/action-gh-release (could also be manually done, but that would probably be more work)

**Comment by jschwe** [comment]
@emilio This PR is not tested, since I obviously don't have permissions to create a tag. So currently the restored release action only creates a "draft" release, so that we could verify first if everything actually worked as expected.

Could you release v0.25 with this? I'd like to get a release with the depfile changes, and while we are at it we could verify if the release action works as expected.

**Comment by jschwe** [comment]
@emilio Would you have time to review this and/or release v0.25.0?

**Comment by jschwe** [comment]
@emilio Would you have time to review this and/or release v0.25.0?

**Review by emilio — APPROVED** [review]

**Pull request merged**
