### PR TITLE
deps: Update syn to 2.0

### PR DESCRIPTION
**Pull request by GrayJack**
The tests failed to me locally. Both without and with this modifications

### CODE REVIEW

**Comment by GrayJack** [comment]
I took the changes of #957 to inspect better what the failures are.

The first one I'm looking at is the `layout.rs`, and I believe that the expected file is wrong, the comments say that `PackedStruct` and `PackedUnion` aren't translated, but they are in the expected file. And with this PR changes, they are not being translated, like the comment in the rust code says it should happen

**Comment by emilio** [comment]
> The tests failed to me locally. Both without and with this modifications

Can you elaborate on how? CI looks green here tho, so that's always something :)

**Comment by emilio** [comment]
I fixed / simplified some of the va-list handling (which otherwise breaks with #970).

**Comment by emilio** [comment]
Thanks!

**Comment by emilio** [comment]
Also if you could file an issue about the tests failing on your machine, it'd be great to get it sorted out.

**Comment by GrayJack** [comment]
> Can you elaborate on how? CI looks green here tho, so that's always something :)

It was the first comment, I fixed the failures in the other commits and forgot to update the comment 😅

**Pull request closed without merging**
